root_key = """ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMOmfeR5oaRJvme4/uFNitESVw\
      dHwACESMqdTSxxIP+UytIBlUU+37/7qyCKkkRWFlvsRyjSQbfnLRE+UZTlH8Y="""

origin = "https://id.noa.re"

[email]
sender_email = "noa@resare.com"
relay_host = "mail.resare.com"
username = "idelephant"
password_file = "/email-password/password"

[persistence]
uri = "ws://surrealdb.surrealdb.svc:8000"
username = "idelephant"
password_file = "/db-password/password"
