[project]
name = "manifest-builder"
version = "0.2.0"
description = "Generate materialized Kubernetes manifests from Helm charts"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click",
    "pyyaml",
    "pystache",
]

[project.scripts]
manifest-builder = "manifest_builder.cli:main"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ty",
    "simple503",
]

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"
