# App configurations reference releases defined in helmfile.yaml.
# The release provides the chart source (repo, chart name, version).

#[[helm]]
#namespace = "cert-manager"
#release = "cert-manager"
#values = ["cert-manager/values.yaml"]
#
[[helm]]
namespace = "surrealdb"
release = "surrealdb"
values = ["surrealdb/values.yaml"]

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"

#
#[[website]]
#name = "id.noa.re"
#namespace = "idelephant"
#image = "nresare/idelephant:latest"
#args = ["-c", "/config/idelephant.toml"]
#[website.config]
#"/config/idelephant.toml" = "idelephant/idelephant.toml"